name: Deploy to Hostinger via FTP

on:
  push:
    branches:
      - main  # Branche à surveiller

jobs:
  ftp-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@v4
        with:
          ftp-server: ftp://213.130.145.71
          ftp-username: ${{ secrets.FTP_USERNAME }}
          ftp-password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./
          git-ftp-args: --insecure 
